# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 407)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 661, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFRZA = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFRZA.setObjectName("menuFRZA")
        self.menuInterpolation = QtWidgets.QMenu(parent=self.menuBar)
        self.menuInterpolation.setObjectName("menuInterpolation")
        self.menuProximity = QtWidgets.QMenu(parent=self.menuBar)
        self.menuProximity.setObjectName("menuProximity")
        self.menuSlope = QtWidgets.QMenu(parent=self.menuBar)
        self.menuSlope.setObjectName("menuSlope")
        self.menuClipping = QtWidgets.QMenu(parent=self.menuBar)
        self.menuClipping.setObjectName("menuClipping")
        self.menuLuLc_indexing = QtWidgets.QMenu(parent=self.menuBar)
        self.menuLuLc_indexing.setObjectName("menuLuLc_indexing")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFRZA = QtGui.QAction(parent=MainWindow)
        self.actionFRZA.setObjectName("actionFRZA")
        self.menuBar.addAction(self.menuFRZA.menuAction())
        self.menuBar.addAction(self.menuInterpolation.menuAction())
        self.menuBar.addAction(self.menuProximity.menuAction())
        self.menuBar.addAction(self.menuSlope.menuAction())
        self.menuBar.addAction(self.menuClipping.menuAction())
        self.menuBar.addAction(self.menuLuLc_indexing.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FRZA"))
        self.menuFRZA.setTitle(_translate("MainWindow", "FRZA"))
        self.menuInterpolation.setTitle(_translate("MainWindow", "Interpolation"))
        self.menuProximity.setTitle(_translate("MainWindow", "Proximity"))
        self.menuSlope.setTitle(_translate("MainWindow", "Slope"))
        self.menuClipping.setTitle(_translate("MainWindow", "Clipping"))
        self.menuLuLc_indexing.setTitle(_translate("MainWindow", "LuLc indexing"))
        self.actionFRZA.setText(_translate("MainWindow", "FRZA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    
    # Load the QSS file
    with open("style.qss", "r") as f:
        qss = f.read()
        app.setStyleSheet(qss)

    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec())

