# Form implementation generated from reading ui file 'tollbox_with_features.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 617)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 371, 61))
        self.groupBox.setObjectName("groupBox")
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.groupBox)
        self.toolButton_2.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton = QtWidgets.QToolButton(parent=self.groupBox)
        self.toolButton.setGeometry(QtCore.QRect(150, 20, 101, 31))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_3 = QtWidgets.QToolButton(parent=self.groupBox)
        self.toolButton_3.setGeometry(QtCore.QRect(280, 20, 71, 31))
        self.toolButton_3.setObjectName("toolButton_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Features"))
        self.toolButton_2.setText(_translate("Dialog", "Proximity"))
        self.toolButton.setText(_translate("Dialog", "Interpolation"))
        self.toolButton_3.setText(_translate("Dialog", "Slope"))
